### ISSUE TITLE
Not a planet!

### ISSUE THREAD

**Issue by rayssags** [rayssags/Topicos_eScience#1]
https://github.com/rayssags/Topicos_eScience/blob/830a4078c1a520304e52d2f67aa6dedfee9c7e4a/pluto.txt#L1

**Comment by ricardogando** [comment]
Not a planet!

**Comment by hmdeabreu** [comment]
Ele tem coração!

**Comment by rayssags** [comment]
Alterado em https://github.com/rayssags/Topicos_eScience/blob/5db3178ff234a050d291ca420b2b42741e77ed7d/pluto.txt#L1

**Comment by ricardogando** [comment]
This was closed by commit https://github.com/rayssags/Topicos_eScience/commit/830a4078c1a520304e52d2f67aa6dedfee9c7e4a
